# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad4be97e06960a154d95c0b704763cdc4194e8df23548eed831e30139b4ab4d565c3c22043de1919f2c9483ae046328be3e6a24d8467cba6343e523a828afb7c

test:
  secret_key_base: 2ec6ff1cf273042ea679a37fa470a024bba0b3b44951733600dcc9b34ab429ba923c7527133176ca8d813f1178da50b63fed59a5e5e4c3265e45802fbdb9c665

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
